local mod = get_mod("ColorCodedHealthbars")

local widgets = {
	{
		setting_id = "general_settings",
		type = "group",
		sub_widgets = {
			{
				setting_id = "show_startup_messages",
				type = "checkbox",
				default_value = true,
				tooltip = "Show mod loading messages in chat",
			},
			{
				setting_id = "max_display_range",
				type = "numeric",
				default_value = 50,
				range = {10, 200},
				tooltip = "Maximum distance (in meters) to display healthbars. Healthbars beyond this range will be hidden to improve performance.",
			},
			{
				setting_id = "always_show_healthbars",
				type = "checkbox",
				default_value = false,
				tooltip = "Force healthbars to stay visible longer and at greater distances for enabled enemy types (overrides fade behavior but respects range limit)",
			},
			{
				setting_id = "show_enemy_names",
				type = "checkbox",
				default_value = true,
				tooltip = "Display enemy names above healthbars. Shows localized breed names like 'Scab Gunner', 'Chaos Spawn', etc.",
			},
			{
				setting_id = "show_names_only",
				type = "checkbox",
				default_value = false,
				tooltip = "Show ONLY enemy names without health bars. Perfect for identifying enemies without visual clutter. Names will use breed-type colors for the tag border.",
			},
			{
				setting_id = "show_tag_indicators",
				type = "checkbox",
				default_value = false,
				tooltip = "Display tag indicators above enemy names. Shows [TAGGED] for player-tagged enemies and [DOG] for arbites dog targets.",
			},
			{
				setting_id = "max_healthbars_shown",
				type = "numeric",
				default_value = 8,
				range = {3, 200},
				tooltip = "Maximum number of healthbars to show at once. Prioritizes closest and most dangerous enemies.",
			},
			{
				setting_id = "hide_full_health",
				type = "checkbox",
				default_value = true,
				tooltip = "Hide healthbars for enemies at full health to reduce clutter. Only shows damaged enemies.",
			},
			{
				setting_id = "priority_system",
				type = "checkbox",
				default_value = true,
				tooltip = "Use smart priority system: Monsters > Specials > Elites > Others. Shows most dangerous enemies first.",
			},
		},
	},
	{
		setting_id = "visibility_settings",
		type = "group",
		sub_widgets = {
			{
				setting_id = "enable_visibility_check",
				type = "checkbox",
				default_value = true,
				tooltip = "Enable line of sight checking - healthbars will fade out when enemies are behind walls or obstacles. Improves realism and reduces visual clutter.",
			},
			{
				setting_id = "visibility_fade_speed",
				type = "numeric",
				default_value = 3.0,
				range = {0.5, 10.0},
				step_size_value = 0.1,
				tooltip = "How quickly healthbars fade in/out when line of sight changes. Higher values = faster transitions. Default: 3.0",
			},
			{
				setting_id = "visibility_behind_walls",
				type = "checkbox",
				default_value = false,
				tooltip = "Show partially transparent healthbars even when enemies are behind walls. If disabled, healthbars completely disappear behind obstacles.",
			},
		},
	},
	{
		setting_id = "visual_settings",
		type = "group",
		sub_widgets = {
			{
				setting_id = "healthbar_width",
				type = "numeric",
				default_value = 120,
				range = {60, 300},
				tooltip = "Width of the health bars in pixels. Default: 120",
			},
			{
				setting_id = "healthbar_height",
				type = "numeric",
				default_value = 6,
				range = {3, 20},
				tooltip = "Height of the health bars in pixels. Default: 6",
			},
			{
				setting_id = "text_size",
				type = "numeric",
				default_value = 20,
				range = {12, 40},
				tooltip = "Font size for enemy names. Default: 20",
			},
			{
				setting_id = "text_offset_y",
				type = "numeric",
				default_value = 8,
				range = {-40, 90},
				tooltip = "Vertical offset of text above the health bar in pixels. Default: 8",
			},
			{
				setting_id = "bar_offset_y",
				type = "numeric",
				default_value = 0,
				range = {-50, 90},
				tooltip = "Vertical offset of the health bar from the enemy's head. Positive moves up, negative moves down. Default: 0",
			},
		},
	},
	{
		setting_id = "visual_enhancement_settings",
		type = "group",
		sub_widgets = {
			{
				setting_id = "bar_border_enabled",
				type = "checkbox",
				default_value = true,
				tooltip = "Add a dark border around health bars for better visibility and contrast",
			},
			{
				setting_id = "bar_border_thickness",
				type = "numeric",
				default_value = 1,
				range = {1, 4},
				tooltip = "Thickness of the health bar border in pixels. Default: 1",
			},
			{
				setting_id = "background_opacity",
				type = "numeric",
				default_value = 180,
				range = {0, 255},
				tooltip = "Opacity of the health bar background (0 = transparent, 255 = fully opaque). Default: 180",
			},
			{
				setting_id = "bar_corner_style",
				type = "dropdown",
				default_value = "standard",
				options = {
					{text = "Standard", value = "standard"},
					{text = "With End Caps", value = "capped"},
				},
				tooltip = "Visual style of health bar - standard rectangular or with rounded end caps",
			},
			{
				setting_id = "text_shadow_enabled",
				type = "checkbox",
				default_value = true,
				tooltip = "Add a subtle shadow behind enemy names for better readability",
			},
			{
				setting_id = "text_outline_enabled",
				type = "checkbox",
				default_value = false,
				tooltip = "Add a dark outline around enemy name text for maximum visibility",
			},
			{
				setting_id = "health_gradient",
				type = "checkbox",
				default_value = true,
				tooltip = "Health bars change color based on current health: Green (full) → Yellow (medium) → Red (low)",
			},
			{
				setting_id = "gradient_intensity",
				type = "numeric",
				default_value = 75,
				range = {0, 100},
				tooltip = "How much the health gradient affects the bar color (0 = breed color only, 100 = full health gradient)",
			},
			{
				setting_id = "smooth_animations",
				type = "checkbox",
				default_value = true,
				tooltip = "Enable smooth animations for health bar changes and fading",
			},
		},
	},
	{
		setting_id = "breed_type_toggles",
		type = "group",
		sub_widgets = {
			{
				setting_id = "show_horde",
				type = "checkbox",
				default_value = false,
				tooltip = "Show healthbars for all horde enemies (Gray color). Can be performance intensive with many enemies.",
			},
			{
				setting_id = "show_roamer",
				type = "checkbox",
				default_value = false,
				tooltip = "Show healthbars for all roamer enemies (Light Gray color). Can be performance intensive with many enemies.",
			},
			{
				setting_id = "show_elite",
				type = "checkbox",
				default_value = true,
				tooltip = "Show healthbars for all elite enemies (Orange colors - ranged vs melee subcategories).",
			},
			{
				setting_id = "show_special",
				type = "checkbox",
				default_value = true,
				tooltip = "Show healthbars for all special enemies (Magenta colors - sniper vs disabler subcategories).",
			},
			{
				setting_id = "show_monster",
				type = "checkbox",
				default_value = true,
				tooltip = "Show healthbars for all monster enemies (Red color).",
			},
			{
				setting_id = "show_captain",
				type = "checkbox",
				default_value = true,
				tooltip = "Show healthbars for all captain enemies (Purple color). Now properly detects both regular captains and cultist captains!",
			},
		},
	},
	{
		setting_id = "basic_color_settings",
		type = "group",
		sub_widgets = {
			
			{
				setting_id = "horde_color_r",
				type = "numeric",
				default_value = 150,
				range = {0, 255},
				tooltip = "Red component for horde enemy healthbars (0-255)",
			},
			{
				setting_id = "horde_color_g",
				type = "numeric",
				default_value = 150,
				range = {0, 255},
				tooltip = "Green component for horde enemy healthbars (0-255)",
			},
			{
				setting_id = "horde_color_b",
				type = "numeric",
				default_value = 150,
				range = {0, 255},
				tooltip = "Blue component for horde enemy healthbars (0-255)",
			},
			{
				setting_id = "monster_color_r",
				type = "numeric",
				default_value = 255,
				range = {0, 255},
				tooltip = "Red component for monster enemy healthbars (0-255)",
			},
			{
				setting_id = "monster_color_g",
				type = "numeric",
				default_value = 0,
				range = {0, 255},
				tooltip = "Green component for monster enemy healthbars (0-255)",
			},
			{
				setting_id = "monster_color_b",
				type = "numeric",
				default_value = 0,
				range = {0, 255},
				tooltip = "Blue component for monster enemy healthbars (0-255)",
			},
		},
	},
	{
		setting_id = "captain_color_settings",
		type = "group",
		sub_widgets = {
			{
				setting_id = "captain_color_r",
				type = "numeric",
				default_value = 128,
				range = {0, 255},
				tooltip = "Red component for captain enemy healthbars (0-255). Default: half of monster red (128). FIXED: Now uses all RGB components correctly!",
			},
			{
				setting_id = "captain_color_g",
				type = "numeric",
				default_value = 0,
				range = {0, 255},
				tooltip = "Green component for captain enemy healthbars (0-255). Default: half of monster green (0). FIXED: Now properly calculated!",
			},
			{
				setting_id = "captain_color_b",
				type = "numeric",
				default_value = 128,
				range = {0, 255},
				tooltip = "Blue component for captain enemy healthbars (0-255). Default: half of monster blue (128). FIXED: Now uses monster blue instead of red!",
			},
		},
	},
	{
		setting_id = "elite_subcategory_colors",
		type = "group",
		sub_widgets = {
			{
				setting_id = "elite_melee_color_r",
				type = "numeric",
				default_value = 255,
				range = {0, 255},
				tooltip = "Red component for melee elite enemies (Ragers, Crushers, etc.)",
			},
			{
				setting_id = "elite_melee_color_g",
				type = "numeric",
				default_value = 165,
				range = {0, 255},
				tooltip = "Green component for melee elite enemies",
			},
			{
				setting_id = "elite_melee_color_b",
				type = "numeric",
				default_value = 0,
				range = {0, 255},
				tooltip = "Blue component for melee elite enemies",
			},
			{
				setting_id = "elite_ranged_color_r",
				type = "numeric",
				default_value = 255,
				range = {0, 255},
				tooltip = "Red component for ranged elite enemies (Gunners, Shocktroopers, etc.)",
			},
			{
				setting_id = "elite_ranged_color_g",
				type = "numeric",
				default_value = 100,
				range = {0, 255},
				tooltip = "Green component for ranged elite enemies",
			},
			{
				setting_id = "elite_ranged_color_b",
				type = "numeric",
				default_value = 0,
				range = {0, 255},
				tooltip = "Blue component for ranged elite enemies",
			},
		},
	},
	{
		setting_id = "special_subcategory_colors",
		type = "group",
		sub_widgets = {
			{
				setting_id = "special_color_r",
				type = "numeric",
				default_value = 255,
				range = {0, 255},
				tooltip = "Red component for generic special enemies (Flamers, Mutants, Berzerkers, etc.)",
			},
			{
				setting_id = "special_color_g",
				type = "numeric",
				default_value = 0,
				range = {0, 255},
				tooltip = "Green component for generic special enemies",
			},
			{
				setting_id = "special_color_b",
				type = "numeric",
				default_value = 255,
				range = {0, 255},
				tooltip = "Blue component for generic special enemies",
			},
			{
				setting_id = "special_sniper_color_r",
				type = "numeric",
				default_value = 255,
				range = {0, 255},
				tooltip = "Red component for sniper specials (Snipers)",
			},
			{
				setting_id = "special_sniper_color_g",
				type = "numeric",
				default_value = 0,
				range = {0, 255},
				tooltip = "Green component for sniper specials",
			},
			{
				setting_id = "special_sniper_color_b",
				type = "numeric",
				default_value = 200,
				range = {0, 255},
				tooltip = "Blue component for sniper specials",
			},
			{
				setting_id = "special_pox_hound_color_r",
				type = "numeric",
				default_value = 200,
				range = {0, 255},
				tooltip = "Red component for Pox Hounds (chaos_hound). Now separate from Trappers!",
			},
			{
				setting_id = "special_pox_hound_color_g",
				type = "numeric",
				default_value = 0,
				range = {0, 255},
				tooltip = "Green component for Pox Hounds",
			},
			{
				setting_id = "special_pox_hound_color_b",
				type = "numeric",
				default_value = 255,
				range = {0, 255},
				tooltip = "Blue component for Pox Hounds",
			},
			{
				setting_id = "special_trapper_color_r",
				type = "numeric",
				default_value = 180,
				range = {0, 255},
				tooltip = "Red component for Trappers (renegade_netgunner). Now separate from Pox Hounds!",
			},
			{
				setting_id = "special_trapper_color_g",
				type = "numeric",
				default_value = 0,
				range = {0, 255},
				tooltip = "Green component for Trappers",
			},
			{
				setting_id = "special_trapper_color_b",
				type = "numeric",
				default_value = 255,
				range = {0, 255},
				tooltip = "Blue component for Trappers",
			},

		},
	},
}

return {
	name = mod:localize("mod_name"),
	description = mod:localize("mod_description"),
	is_togglable = true,
	options = {
		widgets = widgets,
	},
}